[package]
name = "moving_render"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29.15"
softbuffer = "0.4"

[profile.release]
opt-level = 3        # Maximum optimizations (LLVM passes)
lto = "fat"          # Link-Time Optimization across all crates
codegen-units = 1    # Enables better cross-function optimizations at the cost of compile time
panic = "abort"      # Disables stack unwinding code overhead on panics